name: Deploiement formulaire
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Recup du code
        uses: actions/checkout@v4
      - name: Pousse le code sur gh-page
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./
          github_token: ${{secrets.GITHUB_TOKEN}}
permissions:
  contents: write